insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Pasta alla Carbonara', 'PastaCarbonara.png',   15, 'Primo',    'Facile',       'La Carbonara è un primo piatto romano con spaghetti, guanciale, pecorino, uova, pepe e sale. Un tripudio di sapori: il guanciale croccante, la cremosità delle uova, il pecorino saporito. Da provare!');
insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Pasta Cacio e Pepe',   'CacioPepe.png',        15, 'Primo',    'Medio',        'Un classico romano semplice ma gustoso: spaghetti conditi con pecorino romano grattugiato, pepe nero macinato fresco e acqua di cottura per creare una cremina densa.');
insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Pizza Margherita',     'PizzaMargherita.png',  80, 'Primo',    'Medio',        'Un icona della cucina italiana: pomodoro, mozzarella fior di latte, basilico fresco e olio extravergine su una base di pizza croccante.');
insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Pasta alla Norma',     'PastaNorma.png',       25, 'Primo',    'Medio',        'Un piatto siciliano ricco e saporito: melanzane fritte, ricotta salata, pomodoro e basilico su pasta al forno.');
insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Pasta Amatriciana',    'PastaAmatriciana.png', 10, 'Primo',    'Facile',       'Un primo piatto romano con guanciale, pecorino romano, pomodoro, cipolla, peperoncino e vino bianco.');
insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Bistecca di Manzo',    'BisteccaManzo.png',    15, 'Secondo',  'Difficile',    'Un secondo piatto classico e versatile: carne di manzo cotta alla griglia o alla piastra, servita con i tuoi contorni preferiti.');
insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Polpette al Sugo',     'PolpetteSugo.png',     30, 'Secondo',  'Facile',       'Polpette al sugo: sfiziose polpettine di carne in un sugo di pomodoro, un classico italiano da gustare!');
insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Ravioli Cinesi',       'RavioliCinesi.png',    60, 'Antipasto','Difficile',    'I ravioli cinesi, gustosi fagottini di pasta ripieni, simbolo di fortuna. Da provare al vapore, con salsa di soia e aceto di riso!');
insert into recipe (id, name, url_image, cook_time, recipe_type, difficulty, description) values(nextval('recipe_seq'), 'Tiramisu',             'tiramisu.png',         40, 'Dolce',    'Facile',       'Delizioso dolce al cucchiaio con savoiardi, caffè, mascarpone e cacao. Un capolavoro italiano.');


insert into cook (id, name, surname, url_image, year, description) values(nextval('cook_seq'), 'Carlo',      'Cracco',           'CarloCracco.png',             '8-10-1965', 'Nato a Creazzo nel 1965, ha ottenuto 5 stelle Michelin nel corso della sua carriera. Noto per la sua cucina moderna e innovativa, che unisce tradizione e sperimentazione. Ha ottenuto grande popolarità come giudice in programmi televisivi.');
insert into cook (id, name, surname, url_image, year, description) values(nextval('cook_seq'), 'Massimo',    'Bottura',          'MassimoBottura.png',          '30-09-1962','Chef italiano rinomato, nato a Modena nel 1962. Noto per la sua cucina innovativa e creativa, che reinterpreta la tradizione culinaria italiana con un tocco moderno. Famoso per il suo impegno nella lotta contro lo spreco alimentare.');
insert into cook (id, name, surname, url_image, year, description) values(nextval('cook_seq'), 'Joe',        'Bastianich',       'JoeBastianich.png',           '17-09-1968','Nato a New York da genitori italiani, Bastianich ha iniziato la sua carriera lavorando nei ristoranti di famiglia. Ha scritto diversi libri di cucina e partecipato a molti programmi televisivi culinari come MasterChef Italia e USA.');
insert into cook (id, name, surname, url_image, year, description) values(nextval('cook_seq'), 'Enrico',     'Crippa',           'EnricoCrippa.png',            '25-11-1971','Enrico Crippa impara dal nonno la passione per il cibo sano a km zero. Dopo il diploma comincia l’apprendistato a Milano per poi andare all’estero, dove collabora con i migliori chef europei.');
insert into cook (id, name, surname, url_image, year, description) values(nextval('cook_seq'), 'Bruno',      'Barbieri',         'BrunoBarbieri.png',           '12-01-1962','La sua passione per la cucina nasce sin da piccolo, trascorrendo la maggior parte del tempo nella cucina dei nonni. Nel 1990, apre il suo ristorante che gli vale sette stelle Michelin, affermandosi come uno dei più grandi chef italiani.');
insert into cook (id, name, surname, url_image, year, description) values(nextval('cook_seq'), 'Gordon',     'Ramsay',           'GordonRamsay.png',            '8-11-1966', 'Nel 1998 ha aperto il suo primo ristorante, il Gordon Ramsay, che ha ottenuto ben tre stelle Michelin. Da allora, ha aperto una serie di ristoranti di successo in tutto il mondo, ottenendo un totale di 17 stelle Michelin.')


insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Farina 0',         'farina0.png',      'Ingrediente base per pane, pasta e dolci, dona consistenza e struttura alle preparazioni.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Acqua',            'acqua.png',        'Elemento essenziale per la vita, dona idratazione e scioglie gli ingredienti in cucina.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Uova',             'uova.png',         'Un alimento altamente nutriente e versatile, l uovo è una fonte di proteine di alta qualità.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Spaghetti',        'spaghetti.png',    'Un alimento base della cucina italiana, la pasta è costituita principalmente da farina di grano e acqua.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Olio EVO',         'olioDiOliva.png',  'Condimento prezioso dal gusto fruttato, elemento base della dieta mediterranea, utilizzato per cuocere, condire e conservare.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Sale Fino',        'saleFino.png',     'Un condimento cristallino utilizzato per esaltare il sapore dei cibi.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Sale Grosso',      'saleGrosso.png',   'Un sale in grani più grandi, utilizzato per salare acqua di cottura, carne o verdure prima della cottura.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Zucchero',         'zucchero.png',     'Disaccaride bianco estratto da barbabietola o canna da zucchero, usato come dolcificante.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Pepe Nero',        'pepeNero.png',     'Spezia pungente e aromatica, dona carattere a sughi, salse e carni, esaltandone i sapori.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Caffe',            'caffe.png',        'I chicchi di caffè sono i semi del frutto della pianta di caffè, tostati e macinati per preparare la bevanda. Hanno forme diverse e variano in colore dal verde-azzurro al grigio-verde, a seconda della specie.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Savoiardi',        'savoiardi.png',    'I savoiardi sono biscotti friabili e spugnosi, tipicamente usati per il tiramisù, originari della Savoia.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Cipolla Bianca',   'cipollaBianca.png','Un ortaggio dal sapore delicato, utilizzato per soffritti, zuppe e torte salate');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Cipolla Rossa',    'cipollaRossa.png', 'Un ortaggio dal sapore più intenso rispetto alla cipolla bianca, ideale per insalate, pinzimoni e conserve.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Aglio',            'aglio.png',        'Un bulbo aromatico dal gusto pungente, utilizzato per insaporire salse, soffritti e piatti di carne e pesce.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Origano',          'origano.png',      'Erba aromatica dal profumo mediterraneo, esalta il gusto di pizze, focacce e grigliate di verdure.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Basilico',         'basilico.png',     'Erba aromatica dal profumo inconfondibile, regna indiscusso sulla pizza e accompagna pomodori, pasta e insalate.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Prezzemolo',       'prezzemolo.png',   'Erba aromatica dal sapore fresco e delicato, utilizzata per insaporire minestre, salse e secondi piatti.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Passata di Pomodoro',  'passata.png',  'Condimento base per sughi e salse, dona colore e sapore a pizze, pasta e piatti di pesce.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Pomodori',         'pomodori.png',     'Frutti rossi succosi e dal sapore dolce, consumati freschi in insalata, oppure utilizzati per preparare sughi, salse e conserve.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Pomodori Pelati',  'pomodoriPelati.png', 'Un ingrediente base della cucina italiana, utilizzati per preparare sughi, salse e piatti tipici come la pizza e la pasta al pomodoro.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Guanciale',        'guanciale.png',    'Un tipo di pancetta italiana che viene preparata utilizzando il grasso e la carne della guancia del maiale.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Pecorino Romano',  'pecorino.png',     'Il Pecorino Romano è un formaggio italiano stagionato, a pasta dura e dal sapore robusto e salato.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Grana Padano DOP', 'granaPadano.png',  'Formaggio stagionato dal gusto intenso e umami, ideale per grattugiare su primi piatti, risotti e verdure.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Ricotta',          'ricotta.png',      'Formaggio fresco dal sapore delicato e consistenza cremosa, versatile in torte salate, ripieni e salse.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Mozzarella',       'mozzarella.png',   'Formaggio a pasta filata dal sapore dolce e consistenza morbida, protagonista di pizze, insalate e piatti al forno.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Mascarpone',       'mascarpone.png',   'Il Mascarpone è un formaggio fresco italiano, cremoso, dal sapore delicato e leggermente dolce, perfetto per dolci al cucchiaio come il tiramisù.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Zucchine',         'zucchine.png',     'Ortaggi estivi dal sapore delicato, ideali per grigliate, frittate, pasta e minestre.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Broccoli',         'broccoli.png',     'Infiorescenze verdi commestibili, ricche di vitamine e fibre, ideali per primi piatti, contorni e sformati.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Melanzane',        'melanzane.png',    'Ortaggio dal sapore deciso e leggermente amarognolo, protagonista di infinite ricette, dalla classica parmigiana alle gustose polpette.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Insalata',         'insalata.png',     'Verdure a foglia fresca, come lattuga, rucola o valeriana, consumate crude in insalate o come contorno.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Patate',           'patate.png',       'Tuberi amidacei, versatili in cucina, possono essere bolliti, arrostiti, fritti o utilizzati per gnocchi e purè.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Carote',           'carote.png',       'Radici arancioni croccanti e dolciastre, ricche di betacarotene, perfette per insalate, minestroni e stufati.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Bistecca di Manzo','bistecca.png',     'Formaggio stagionato dal gusto intenso e umami, ideale per grattugiare su primi piatti, risotti e verdure.');
insert into ingredient (id, name, url_image, description) values(nextval('ingredient_seq'), 'Limone',           'limone.png',       'Un agrume dal gusto aspro e rinfrescante, utilizzato per condire salse, pesce e carne, e per preparare granite e limonate.');

